version: "3.9"
services:
    nginx:
        build:
            context: nginx
        ports:
            - "3000:8080"
        depends_on:
            - frontend

    frontend:
        build:
            context: frontend
        depends_on:
            - backend

    backend:
        build:
            context: backend
        restart: always
        environment:
            PGSTRING: postgres://postgres:example@db:5432/postgres
        depends_on:
            - db

    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: example

    # detectron2:
    #     build: detectron2
    #     environment:
    #         BASE_ADDRESS: backend:4000
    #         FETCH_INTERVAL: 10
    #     depends_on:
    #         - backend
    # yolo:
    #     build: yolo
    #     environment:
    #         BASE_ADDRESS: backend:4000
    #         FETCH_INTERVAL: 10
    #     depends_on:
    #       - backend
